# Generated by Django 3.0.1 on 2021-01-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_url', models.CharField(max_length=255)),
                ('num', models.BigIntegerField(default=0)),
                ('type', models.CharField(max_length=255)),
                ('diameter', models.IntegerField(default=0)),
                ('airflow', models.IntegerField(default=0)),
                ('airflow_unit', models.CharField(choices=[('M3S', 'm³/s'), ('M3H', 'm³/h'), ('CFM', 'CFM')], default='M3S', max_length=3)),
                ('pressure', models.IntegerField(default=0)),
                ('pressure_unit', models.CharField(choices=[('PA', 'Pa'), ('WC', 'WC')], default='PA', max_length=2)),
                ('efficiently', models.FloatField(default=0)),
            ],
        ),
    ]
