# Generated by Django 3.0.1 on 2021-01-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fan',
            name='pressure',
            field=models.FloatField(default=0),
        ),
    ]
